<a href="https://colab.research.google.com/github/Megh-ops/Rule-Based-Sentiment-Analysis/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

x; = pd.read_excel (r'/Comments - PFA S2.xlsx')
print (df)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Comments - PFA S2.xlsx")
df

                    Name  ... Reply Count
0             Dice Media  ...         347
1     A-10 Sneha Gaikwad  ...           0
2          Priyank Khare  ...           0
3           Manish Kumar  ...           0
4           Manish Kumar  ...           0
...                  ...  ...         ...
5662            eyeconic  ...           1
5663               rehan  ...           0
5664    Amit Srivasatava  ...           3
5665        nitish rawat  ...           0
5666    Amit Srivasatava  ...           1

[5667 rows x 5 columns]

### Emoji & Emoticon handling

In [ ]:
!pip install emot

Collecting emot
  Downloading emot-3.1-py3-none-any.whl (61 kB)
     |‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 61 kB 14 kB/s
Installing collected packages: emot
Successfully installed emot-3.1

In [ ]:
df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

                    Name  ... Reply Count
0             Dice Media  ...         347
1     A-10 Sneha Gaikwad  ...           0
2          Priyank Khare  ...           0
3           Manish Kumar  ...           0
4           Manish Kumar  ...           0
...                  ...  ...         ...
5662            eyeconic  ...           1
5663               rehan  ...           0
5664    Amit Srivasatava  ...           3
5665        nitish rawat  ...           0
5666    Amit Srivasatava  ...           1

[5667 rows x 5 columns]

### Preprocessing

In [ ]:
df=df.drop(['Name','Time'], axis=1)
df.head(5)

                                             Comment  Likes  Reply Count
0  How did you guys like the episode? ‚ù§Ô∏è Tell us ...   3865          347
1                                           Venkat üòÇ      0            0
2                            This show is aging well      0            0
3  .<br><br><br><br><br><br><br><br><br><br><br><...      0            0
4                                                  .      0            0

In [ ]:
def clean(text):

    text = re.sub('[^A-Za-z]+', ' ', text)
    return text

df['Cleaned Comments'] = df['Comment'].astype(str).apply(clean)

In [ ]:
df.head()

                                             Comment  ...                                   Cleaned Comments
0  How did you guys like the episode? ‚ù§Ô∏è Tell us ...  ...  How did you guys like the episode Tell us in c...
1                                           Venkat üòÇ  ...                                            Venkat
2                            This show is aging well  ...                            This show is aging well
3  .<br><br><br><br><br><br><br><br><br><br><br><...  ...   br br br br br br br br br br br br br br br ...
4                                                  .  ...

[5 rows x 4 columns]

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk import pos_tag
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('wordnet')
from nltk.corpus import wordnet
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [ ]:
pos_dict = {'J':wordnet.ADJ, 'V':wordnet.VERB, 'N':wordnet.NOUN, 'R':wordnet.ADV}
def token_stop_pos(text):
    tags = pos_tag(word_tokenize(text))
    newlist = []
    for word, tag in tags:
        if word.lower() not in set(stopwords.words('english')):
          newlist.append(tuple([word, pos_dict.get(tag[0])]))

        
    return newlist

df['POS tagged'] = df['Cleaned Comments'].apply(token_stop_pos)

In [ ]:
df.head()

                                             Comment  ...                                         POS tagged
0  How did you guys like the episode? ‚ù§Ô∏è Tell us ...  ...  [(guys, v), (like, None), (episode, n), (Tell,...
1                                           Venkat üòÇ  ...                                      [(Venkat, n)]
2                            This show is aging well  ...                 [(show, n), (aging, v), (well, r)]
3  .<br><br><br><br><br><br><br><br><br><br><br><...  ...  [(br, n), (br, n), (br, n), (br, n), (br, n), ...
4                                                  .  ...                                                 []

[5 rows x 5 columns]

In [ ]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
def lemmatize(pos_data):
    lemma_rew = " "
    for word, pos in pos_data:
    if not pos:
        lemma = word
        lemma_rew = lemma_rew + " " + lemma
    else:
        lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        lemma_rew = lemma_rew + " " + lemma
    return lemma_rew

df['Lemma'] = df['POS tagged'].apply(lemmatize)
mydata.head()